[package]
name = "space-menace"
version = "0.1.0"
authors = ["Kumar Ankur <kmrankur@outlook.com>"]
edition = "2018"

[dependencies]
amethyst = { path = "../amethyst", features = ["nightly", "metal", "json"] }
serde = "*"
log = "*"
specs-derive = "*"

[features]
default = ["metal"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]

